apiVersion: apps/v1
kind: Deployment
metadata:
  name: soft-street-deployment
  labels:
    app: soft-street
spec:
  replicas: 2
  selector:
    matchLabels:
      app: soft-street
  template:
    metadata:
      labels:
        app: soft-street
    spec:
      containers:
      - name: soft-street-container
        image: varma8k8k/soft-street:{{tag}}
        ports:
        - containerPort: 80
